### PR TITLE
Fix: add gnu99 to cflag; fix the manifest.in

### PR DESCRIPTION
**Pull request by taoliu**
To compile `fermi-lite` and `simde`, it seems that `-std=gnu99` has to be turned on on certain versions of gcc. Also, since we don't need 'OpenMP' support currently, I removed the `-fopenmp` flags. The MANIFEST.in file has been fixed to correctly include the source code files, and to exclude the cython generated C codes. When user install MACS3, cython will generate new C codes using the cython installed on user's system.

### CODE REVIEW

**Comment by taoliu** [comment]
non-X64 testing has been turned off for this PR.

**Comment by taoliu** [comment]
@mr-c Thanks for the comment! I will try this solution. Also, will use https://github.com/simd-everywhere/simde-no-tests instead of https://github.com/simd-everywhere/simde

**Comment by taoliu** [comment]
@mr-c I keep seeing `gcc: error: unrecognized command line option ‘-fopenmp-simd’` under gcc 4.8.5 on our computer server. Did you see this before? 

```
$gcc -pthread -B /mnt/lustre/users/tliu/miniconda3/envs/macs300a4/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/lustre/users/tliu/miniconda3/envs/macs300a4/lib/python3.8/site-packages/numpy/core/include -I./ -I./MACS3/fermi-lite/ -I./MACS3/Signal/ -I/mnt/lustre/users/tliu/miniconda3/envs/macs300a4/include/python3.8 -c MACS3/Signal/RACollection.c -o build/temp.linux-x86_64-3.8/MACS3/Signal/RACollection.o -w -Ofast -g0 -std=gnu99 -DUSE_SIMDE -DSIMDE_ENABLE_NATIVE_ALIASES -fopenmp-simd -DSIMDE_ENABLE_OPENMP -v
Using built-in specs.
COLLECT_GCC=gcc
gcc: error: unrecognized command line option ‘-fopenmp-simd’
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
```

**Comment by mr-c** [comment]
> @mr-c I keep seeing `gcc: error: unrecognized command line option ‘-fopenmp-simd’` under gcc 4.8.5 on our computer server. Did you see this before? 
> 
> ```
> $gcc -pthread -B /mnt/lustre/users/tliu/miniconda3/envs/macs300a4/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/mnt/lustre/users/tliu/miniconda3/envs/macs300a4/lib/python3.8/site-packages/numpy/core/include -I./ -I./MACS3/fermi-lite/ -I./MACS3/Signal/ -I/mnt/lustre/users/tliu/miniconda3/envs/macs300a4/include/python3.8 -c MACS3/Signal/RACollection.c -o build/temp.linux-x86_64-3.8/MACS3/Signal/RACollection.o -w -Ofast -g0 -std=gnu99 -DUSE_SIMDE -DSIMDE_ENABLE_NATIVE_ALIASES -fopenmp-simd -DSIMDE_ENABLE_OPENMP -v
> Using built-in specs.
> COLLECT_GCC=gcc
> gcc: error: unrecognized command line option ‘-fopenmp-simd’
> Target: x86_64-redhat-linux
> Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
> Thread model: posix
> gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
> ```

Must not be recognized in that old version. @nemequ , does ‘-fopenmp-simd' have a different name in old GCC versions?

**Comment by nemequ** [comment]
Unfortunately no, `-fopenmp-simd` was added in 4.9 and was a new feature.  `-fopenmp` (enabling full OpenMP support instead of just OpenMP SIMD) wouldn't do you any good either, since 4.9 is the first version of GCC which added support for OpenMP 4 (which is when SIMD was added to OpenMP), and OpenMP SIMD is the only part of OpenMP that SIMDe uses.

When testing SIMDe we deal with this by [checking for compiler support for the flag](https://github.com/simd-everywhere/simde/blob/c5945ca399b5f3f7f39e7d8389146f97da2e2349/test/meson.build#L19) in the build system (`-fopenmp-simd` is for GCC and clang, `-qopenmp-simd` is for ICC).  I'm not sure how to do that in a `setup.py`, but I'd be shocked if it weren't possible.  You can also just remove `-fopenmp-simd` and `-DSIMDE_ENABLE_OPENMP` completely, but performance of some functions may suffer.

**Comment by taoliu** [comment]
@nemequ Thanks! I will let setup.py check gcc version then remove the `-fopenmp-simd -DSIMDE_ENABLE_OPENMP` flag if the version is lower than 4.9.

**Pull request merged**
